# Generated by Django 3.0.7 on 2020-07-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
