# Generated by Django 3.0.7 on 2020-07-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
