# Generated by Django 3.0.7 on 2020-07-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200705_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.CharField(max_length=200),
        ),
    ]
