# Generated by Django 3.0.7 on 2020-07-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend',
            field=models.ManyToManyField(to='blog.CustomUser'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
