# Generated by Django 3.0.7 on 2020-08-15 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='date_begin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
